/**
 * The melody library for Practice 3, and the tasks it sets.
 *
 * Deliberately thin. A melody here is a short single-note idea — no chords, no
 * backing — recorded on piano or guitar, and the exercise never needs to know
 * anything about its contents. There is no pitch detection, no MIDI and no
 * analysis in this version: the comparison is the listener's ears, so the file
 * plus a title is the whole model.
 *
 * Audio lives in `public/Practice/Melodies/`. The placeholders generated by
 * `scripts/generate-placeholder-melodies.mjs` are WAVs, which .gitignore keeps
 * out of the repo; the real takes will be mp3s. Point `audioUrl` at whichever is
 * on disk — nothing else cares.
 */

export interface PracticeMelody {
    /** Stable across renames; what a completion is recorded against. */
    id: string;
    title: string;
    /** Piano or guitar, so someone can pick the one they can play back on. */
    instrument: 'piano' | 'guitar';
    audioUrl: string;
    /** Off until the file is really there — a melody with no audio is a dead card. */
    available: boolean;
}

const DIR = '/Practice/Melodies';

export const MELODIES: PracticeMelody[] = [
    {
        id: 'morning-line',
        title: 'Morning line',
        instrument: 'piano',
        audioUrl: `${DIR}/morning-line.wav`,
        available: true,
    },
    {
        id: 'slow-turn',
        title: 'Slow turn',
        instrument: 'piano',
        audioUrl: `${DIR}/slow-turn.wav`,
        available: true,
    },
    {
        id: 'little-runner',
        title: 'Little runner',
        instrument: 'guitar',
        audioUrl: `${DIR}/little-runner.wav`,
        available: true,
    },
    {
        id: 'open-question',
        title: 'Open question',
        instrument: 'guitar',
        audioUrl: `${DIR}/open-question.wav`,
        available: true,
    },
];

/**
 * What to do with the melody once you have heard it.
 *
 * Four, because four is what fits on one screen without scrolling and because
 * each asks for a different kind of change: two hold one dimension while moving
 * the other, one rewrites only the last bar, and one answers rather than alters.
 * `id` is stable; the copy is translated.
 */
export const VARIATION_TASKS = [
    { id: 'new-notes', labelKey: 'practice.mv_task_new_notes' },
    { id: 'new-rhythm', labelKey: 'practice.mv_task_new_rhythm' },
    { id: 'new-ending', labelKey: 'practice.mv_task_new_ending' },
    { id: 'answer', labelKey: 'practice.mv_task_answer' },
] as const;

export type VariationTaskId = (typeof VARIATION_TASKS)[number]['id'];

/** The melody someone starts on: the first one whose audio actually exists. */
export function firstPlayableMelody(list: PracticeMelody[] = MELODIES): PracticeMelody | null {
    return list.find(m => m.available) ?? null;
}
