import 'server-only';

/**
 * Offline rhyme / near-rhyme / synonym lookup for Norwegian and Swedish.
 *
 * Swedish and Norwegian spelling maps to pronunciation regularly enough that a
 * rhyme is a suffix match from the last stressed vowel, so this needs no model.
 * It replaces a Gemini-backed implementation that burned a per-project quota
 * shared by every user, failed silently once that quota ran out, and returned
 * invented words. This is deterministic, instant and free.
 *
 * Indexes are generated by scripts/build-lexicon.mjs. English is not handled
 * here — the route keeps using Datamuse, which is free, native and needs no key.
 *
 * The data is server-side only, deliberately. See vendor/lexicon/README.md.
 */

export type LexiconMode = 'rhyme' | 'near' | 'synonym';
export type LexiconLang = 'sv' | 'no';

export interface LexiconEntry {
    word: string;
    syllables: number;
    score: number;
}

interface LexiconData {
    /** rhyme key -> word prefixes; the key is re-appended to rebuild each word. */
    rhyme: Record<string, string[]>;
    /** vowel skeleton of the last two syllables -> whole words. */
    near: Record<string, string[]>;
    syn: Record<string, string[]>;
}

const VOWELS = 'aeiouyåäöæø';
const MAX_RESULTS = 40;

// Parsing a few MB of JSON is not free, so each language is loaded at most once
// per server instance and then reused. Loads are memoised by promise so that
// concurrent first requests don't each kick off their own parse.
const loaders: Partial<Record<LexiconLang, Promise<LexiconData>>> = {};

function load(lang: LexiconLang): Promise<LexiconData> {
    if (!loaders[lang]) {
        loaders[lang] = (lang === 'sv'
            ? import('./data/sv.json')
            : import('./data/no.json')
        ).then(mod => (mod.default ?? mod) as unknown as LexiconData);
    }
    return loaders[lang]!;
}

export function normalizeWord(word: string): string {
    return word.trim().toLowerCase().replace(/[^a-zåäöæøéèêüàáóç]/g, '');
}

/** Consecutive vowels count as one syllable ("hjärta" -> 2, "kärleken" -> 3). */
function countSyllables(word: string): number {
    let count = 0;
    let inVowelRun = false;
    for (const ch of word) {
        const isVowel = VOWELS.includes(ch);
        if (isVowel && !inVowelRun) count++;
        inVowelRun = isVowel;
    }
    return Math.max(1, count);
}

function rhymeKey(word: string): string | null {
    const positions: number[] = [];
    for (let i = 0; i < word.length; i++) {
        if (VOWELS.includes(word[i])) positions.push(i);
    }
    if (positions.length === 0) return null;
    return word.slice(positions[positions.length - (positions.length >= 2 ? 2 : 1)]);
}

function assonanceKey(word: string): string | null {
    const vowels = [...word].filter(c => VOWELS.includes(c));
    if (vowels.length === 0) return null;
    return vowels.slice(-2).join('-');
}

/** Buckets arrive already ordered best-first, so score is derived from position.
 *  The shape matches what Datamuse returns for English so the client can treat
 *  every language identically. */
function toEntries(words: string[]): LexiconEntry[] {
    return words.slice(0, MAX_RESULTS).map((word, i) => ({
        word,
        syllables: countSyllables(word),
        score: 1000 - i * 5,
    }));
}

export async function lookup(
    rawWord: string,
    mode: LexiconMode,
    lang: LexiconLang,
): Promise<LexiconEntry[]> {
    const word = normalizeWord(rawWord);
    if (word.length < 2) return [];

    const data = await load(lang);

    if (mode === 'synonym') {
        return toEntries(data.syn[word] ?? []);
    }

    if (mode === 'rhyme') {
        const key = rhymeKey(word);
        if (!key) return [];
        const prefixes = data.rhyme[key];
        if (!prefixes) return [];
        return toEntries(
            prefixes.map(prefix => prefix + key).filter(candidate => candidate !== word),
        );
    }

    // Near rhyme: same vowel music, different consonants. Anything that already
    // rhymes perfectly is excluded so the two modes return genuinely different
    // lists rather than one being a superset of the other.
    const key = assonanceKey(word);
    if (!key) return [];
    const candidates = data.near[key];
    if (!candidates) return [];

    const perfect = rhymeKey(word);
    return toEntries(
        candidates.filter(candidate => candidate !== word && (!perfect || !candidate.endsWith(perfect))),
    );
}
