import 'server-only';

/**
 * Offline rhyme / near-rhyme / synonym lookup for English, Norwegian and Swedish.
 *
 * All three languages are phoneme-keyed: English from CMUdict, Norwegian and
 * Swedish from the NST pronunciation lexicons (Språkbanken). A rhyme is
 * identical sounds from the last stressed vowel onward — which spelling cannot
 * express in any of the three ("though"/"tough"; "mig" is pronounced "mej" and
 * rhymes with "dig"/"nej", not "krig"). Ranking is corpus-frequency based.
 *
 * This replaces a Gemini-backed implementation that burned a shared quota,
 * failed silently when it ran out, and invented words; and a Datamuse
 * dependency that was unreachable from Cloud Function egress IPs. This is
 * deterministic, instant and free.
 *
 * Indexes are generated by scripts/build-lexicon.mjs. The data is server-side
 * only, deliberately. See vendor/lexicon/README.md.
 */

export type LexiconMode = 'rhyme' | 'near' | 'synonym';
export type LexiconLang = 'sv' | 'no' | 'en';

export interface LexiconEntry {
    word: string;
    syllables: number;
    score: number;
}

interface LexiconData {
    /** phonetic rhyme key -> whole words sharing that sound, best-ranked first. */
    rhyme: Record<string, string[]>;
    /** stressed-vowel (assonance) key -> whole words. */
    near: Record<string, string[]>;
    syn: Record<string, string[]>;
    /** word -> syllable count, from its pronunciation. */
    syllables?: Record<string, number>;
    /** word -> [rhymeKey, nearKey] for corpus-frequent words. Exists because a
     *  common word can be frequency-ranked out of its own oversubscribed bucket
     *  and then be unable to look itself up via the reverse index alone. */
    keys?: Record<string, [string, string]>;
}

/**
 * Buckets are keyed by phonemes, so a query word's key can't be derived from
 * its letters. Rather than ship the pronunciation lexicons a second time just
 * to look keys up, the reverse map is built from the buckets themselves on
 * first use — same data, no extra bytes.
 */
interface ReverseIndex {
    rhymeKeyOf: Map<string, string>;
    nearKeyOf: Map<string, string>;
}

const VOWELS = 'aeiouyåäöæø';
const MAX_RESULTS = 40;

// Parsing a few MB of JSON is not free, so each language is loaded at most once
// per server instance and then reused. Loads are memoised by promise so that
// concurrent first requests don't each kick off their own parse.
const loaders: Partial<Record<LexiconLang, Promise<LexiconData>>> = {};
const reverseIndexes = new WeakMap<LexiconData, ReverseIndex>();

function load(lang: LexiconLang): Promise<LexiconData> {
    if (!loaders[lang]) {
        loaders[lang] = (
            lang === 'sv' ? import('./data/sv.json')
            : lang === 'no' ? import('./data/no.json')
            : import('./data/en.json')
        ).then(mod => (mod.default ?? mod) as unknown as LexiconData);
    }
    return loaders[lang]!;
}

function reverseIndex(data: LexiconData): ReverseIndex {
    let index = reverseIndexes.get(data);
    if (index) return index;

    index = { rhymeKeyOf: new Map(), nearKeyOf: new Map() };
    for (const [key, words] of Object.entries(data.rhyme)) {
        for (const word of words) if (!index.rhymeKeyOf.has(word)) index.rhymeKeyOf.set(word, key);
    }
    for (const [key, words] of Object.entries(data.near)) {
        for (const word of words) if (!index.nearKeyOf.has(word)) index.nearKeyOf.set(word, key);
    }
    reverseIndexes.set(data, index);
    return index;
}

export function normalizeWord(word: string): string {
    return word.trim().toLowerCase().replace(/[^a-zåäöæøéèêüàáóç]/g, '');
}

/** Consecutive vowels count as one syllable ("hjärta" -> 2, "kärleken" -> 3). */
function countSyllables(word: string): number {
    let count = 0;
    let inVowelRun = false;
    for (const ch of word) {
        const isVowel = VOWELS.includes(ch);
        if (isVowel && !inVowelRun) count++;
        inVowelRun = isVowel;
    }
    return Math.max(1, count);
}

/** Buckets arrive already ordered best-first, so score is derived from position.
 *  The shape matches what Datamuse returns for English so the client can treat
 *  every language identically. */
function toEntries(words: string[], data?: LexiconData): LexiconEntry[] {
    return words.slice(0, MAX_RESULTS).map((word, i) => ({
        word,
        // English syllable counts come from CMUdict, since counting vowel letters
        // gets English wrong ("rhythm" has none, "queue" has four).
        syllables: data?.syllables?.[word] ?? countSyllables(word),
        score: 1000 - i * 5,
    }));
}

/**
 * Candidate base forms for an inflected word, best guess first, per language.
 *
 * Deliberately a handful of suffix rules rather than a real morphological
 * analyser: the cost of a wrong guess is one failed map lookup, and every
 * candidate is checked against the dictionary before use, so nothing invented
 * can reach the user.
 *
 * The Nordic rules exist because the thesauri index lemmas while songwriters
 * click whatever form is in the lyric — "hjärtat" (definite), "drømmer"
 * (present) — and English-only stripping left those returning nothing.
 */
function baseForms(word: string, lang: LexiconLang): string[] {
    const candidates: string[] = [];
    const add = (form: string) => {
        if (form.length >= 2 && form !== word && !candidates.includes(form)) candidates.push(form);
    };

    if (lang === 'en') {
        if (word.endsWith('ies')) add(word.slice(0, -3) + 'y');
        if (word.endsWith('ied')) add(word.slice(0, -3) + 'y');
        if (word.endsWith('es')) add(word.slice(0, -2));
        if (word.endsWith('s') && !word.endsWith('ss')) add(word.slice(0, -1));
        if (word.endsWith('ing')) {
            add(word.slice(0, -3));
            add(word.slice(0, -3) + 'e');
        }
        if (word.endsWith('ed')) {
            add(word.slice(0, -2));
            add(word.slice(0, -1));
        }
        if (word.endsWith('ly')) add(word.slice(0, -2));
    } else {
        // Swedish/Norwegian nominal and verbal endings, longest first so
        // "hjärtat" tries "hjärta" before "hjärtat"-minus-one-letter noise.
        // Both languages share most of these; wrong guesses are filtered by
        // the dictionary check at the call site.
        const suffixes = lang === 'sv'
            ? ['heterna', 'heten', 'arna', 'erna', 'orna', 'ande', 'ende', 'ade', 'na', 'en', 'et', 'ar', 'er', 'or', 'at', 'a', 't', 's', 'n']
            : ['hetene', 'heten', 'ene', 'ane', 'ende', 'te', 'en', 'et', 'er', 'a', 'e', 't', 's'];
        for (const suffix of suffixes) {
            if (word.length - suffix.length >= 3 && word.endsWith(suffix)) {
                const stem = word.slice(0, -suffix.length);
                add(stem);
                // Restore a stripped final vowel: "hjärtat" -> "hjärta", "drømmer" -> "drømme".
                add(stem + (lang === 'sv' ? 'a' : 'e'));
            }
        }
    }

    // Doubled consonant before the suffix: "running" -> "run", "stopped" -> "stop".
    for (const stem of [...candidates]) {
        if (stem.length >= 3 && stem[stem.length - 1] === stem[stem.length - 2]) {
            add(stem.slice(0, -1));
        }
    }
    return candidates;
}

export async function lookup(
    rawWord: string,
    mode: LexiconMode,
    lang: LexiconLang,
): Promise<LexiconEntry[]> {
    const word = normalizeWord(rawWord);
    if (word.length < 2) return [];

    const data = await load(lang);

    if (mode === 'synonym') {
        const direct = data.syn[word];
        if (direct) return toEntries(direct, data);
        // WordNet indexes lemmas, not inflections, so "lets" and "dreaming" find
        // nothing on their own. Songwriters click whatever form is in the line, so
        // fall back to the plausible base forms rather than returning empty.
        for (const candidate of baseForms(word, lang)) {
            const found = data.syn[candidate];
            if (found) return toEntries(found, data);
        }
        return [];
    }

    // English is keyed by pronunciation, so it resolves its key by lookup rather
    // than by inspecting the spelling — "though", "through" and "tough" share an
    // ending and rhyme with none of each other.
    // One path for every language: all three are phoneme-keyed, so the word's
    // key is resolved by lookup rather than derived from spelling —
    // "though"/"through"/"tough" share an ending in English exactly the way
    // "mig"/"krig" do in Swedish, and rhyme with none of each other.
    //
    // Nordic data ships an explicit key map for corpus-frequent words and uses
    // ONLY that: its buckets hold ~900k words, and a reverse index over them
    // would cost a couple hundred MB of Map on a function whose whole heap is
    // around 100 MB. English has no key map and small buckets (~130k entries),
    // so it keeps the reverse index. A Nordic word outside the frequency list
    // returns nothing — the honest trade against an OOM'd server.
    const resolveFor = (w: string, which: 0 | 1): string | undefined =>
        data.keys
            ? data.keys[w]?.[which]
            : which === 0
                ? reverseIndex(data).rhymeKeyOf.get(w)
                : reverseIndex(data).nearKeyOf.get(w);

    const resolve = (which: 0 | 1): string | undefined => {
        const direct = resolveFor(word, which);
        if (direct) return direct;
        // Compound-tail fallback. Some words can't carry their own index entry —
        // "something"'s final syllable is unstressed, so no stress-based key ever
        // lands on the "-thing" a songwriter hears — and unknown words aren't in
        // the index at all. But if a word ENDS in a word the index does know
        // ("something" → "thing", "moonlight" → "light"), that tail's sound is the
        // compound's rhyme. Spelling-based, deliberately as a last resort only:
        // every candidate tail must itself be an indexed word, so nothing is
        // guessed from raw letters.
        for (let i = 1; i <= word.length - 3; i++) {
            const key = resolveFor(word.slice(i), which);
            if (key) return key;
        }
        return undefined;
    };

    if (mode === 'rhyme') {
        const key = resolve(0);
        if (!key) return [];
        return toEntries((data.rhyme[key] ?? []).filter(w => w !== word), data);
    }

    // Near rhyme: same stressed-vowel music, different consonants. Anything that
    // already rhymes perfectly is excluded so the two modes return genuinely
    // different lists rather than one being a superset of the other.
    const nearKey = resolve(1);
    if (!nearKey) return [];
    const perfectKey = resolve(0);
    const perfect = new Set(perfectKey ? data.rhyme[perfectKey] ?? [] : []);
    return toEntries(
        (data.near[nearKey] ?? []).filter(w => w !== word && !perfect.has(w)),
        data,
    );
}
